// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v5"
	"go-crud/db"
	"go-crud/handler"
	"go-crud/store"
)

// Injectors from wire.go:

func InitializeApp() (*echo.Echo, error) {
	sqlDB, err := db.Connect()
	if err != nil {
		return nil, err
	}
	taskStore := store.NewTaskStore(sqlDB)
	taskHandler := handler.NewTaskHandler(taskStore)
	echoEcho := NewEcho(taskHandler)
	return echoEcho, nil
}
